### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by AiZUBI** [NVIDIA-AI-IOT/jetson-copilot#15]
Hi there,
I've just made a clean flash of an AGX Orin dev kit and now trying to setup jetson-copilot. After starting the  ollama server I get this error message when trying to connect to localhost. Any idea why the connection is refused?

2024-11-28 17:08:58.946 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/opt/jetson_copilot/app/app.py", line 42, in <module>
    models = [model["name"] for model in ollama.list()["models"]]
  File "/usr/local/lib/python3.10/dist-packages/ollama/_client.py", line 333, in list
    return self._request('GET', '/api/tags').json()
  File "/usr/local/lib/python3.10/dist-packages/ollama/_client.py", line 69, in _request
    response = self._client.request(method, url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

**Comment by AiZUBI** [comment]
jetson@ubuntu:~/jetson-copilot$ ./launch_jetson_copilot.sh
ARCH:  aarch64
L4T_VERSION:  36.4.0
+ JTOP_SOCKET=
+ JTOP_SOCKET_FILE=/run/jtop.sock
+ '[' -S /run/jtop.sock ']'
+ JTOP_SOCKET='-v /run/jtop.sock:/run/jtop.sock'
+ '[' aarch64 = aarch64 ']'
+ verions_numbers=(${L4T_VERSION//./ })
+ L4T_VERSION_MAJOR=36
+ '[' 36 == 35 ']'
+ '[' 36 == 36 ']'
+ log 'JetPack 6.x :'
+ test -n 'JetPack 6.x :'
+ printf '\033[0;93mJetPack 6.x :\033[0m\n'
JetPack 6.x :
+ CONTAINER_TAG=r36.3.0
+ cat /proc/device-tree/model
+ pid=21056
+ PID_LIST+=' 21056'
+ echo '#############################  21056 added to PID_LIST'
#############################  21056 added to PID_LIST
+ docker run --runtime nvidia -it --rm --network host --volume /tmp/argus_socket:/tmp/argus_socket --volume /etc/enctune.conf:/etc/enctune.conf --volume /etc/nv_tegra_release:/etc/nv_tegra_release --volume /tmp/nv_jetson_model:/tmp/nv_jetson_model --volume /var/run/dbus:/var/run/dbus --volume /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket --volume /var/run/docker.sock:/var/run/docker.sock --volume /home/jetson/jetson-copilot/Documents:/opt/jetson_copilot/Documents --volume /home/jetson/jetson-copilot/Indexes:/opt/jetson_copilot/Indexes --volume /home/jetson/jetson-copilot/logs:/data/logs --volume /home/jetson/jetson-copilot/ollama_models://data/models/ollama/models --volume /home/jetson/jetson-copilot/streamlit_app:/opt/jetson_copilot/app --device /dev/snd --device /dev/bus/usb -v /run/jtop.sock:/run/jtop.sock dustynv/jetson-copilot:r36.3.0 bash -c '/start_ollama && cd /opt/jetson_copilot/app/ && streamlit run ./app.py'
+ tee -a ./logs/container.log
+ echo ''
+ zenity --progress --text 'Display test' --auto-close
+ '[' 0 -eq 0 ']'
                 + pid=21098
                            + PID_LIST+=' 21098'
                                                + trap 'kill  21056 21098' SIGINT
 + chromium --profile-directory=Default '--app=data:text/html,<html><body><script>window.resizeTo(560,1080);window.moveTo(1300,120);window.location='\''http://localhost:8501'\'';</script></body></html>'
                                          + echo 'Parallel processes have started'
  Parallel processes have started
                                 + wait 21056 21098
                                                   2024/11/29 14:48:48.430437 cmd_run.go:1276: WARNING: cannot create user data directory: failed to verify SELinux context of /home/jetson/snap: exit status 255

Starting ollama server

Opening in existing browser session.
                                    Couldn't find '/root/.ollama/id_ed25519'. Generating new private key.
Your new public key is: 

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAc3SsTDCWbBGjM+c5DDjOvLoW/IL7IKKTWZzAwSb+op

2024/11/29 13:48:48 routes.go:1077: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE: OLLAMA_LLM_LIBRARY: OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MAX_VRAM:0 OLLAMA_MODELS:/data/models/ollama/models OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://*] OLLAMA_RUNNERS_DIR: OLLAMA_SCHED_SPREAD:false OLLAMA_TMPDIR: ROCR_VISIBLE_DEVICES:]"
time=2024-11-29T13:48:48.638Z level=INFO source=images.go:751 msg="total blobs: 0"
time=2024-11-29T13:48:48.638Z level=INFO source=images.go:758 msg="total unused blobs removed: 0"
time=2024-11-29T13:48:48.638Z level=INFO source=routes.go:1124 msg="Listening on [::]:11434 (version 0d4dd70)"
time=2024-11-29T13:48:48.639Z level=INFO source=payload.go:30 msg="extracting embedded files" dir=/tmp/ollama1823698012/runners

OLLAMA_MODELS /data/models/ollama/models
OLLAMA_LOGS   /data/logs/ollama.log

ollama server is now started, and you can run commands here like 'ollama run llama3'


Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2024-11-29 13:49:28.672 Did not auto detect external IP.
Please go to https://docs.streamlit.io/ for debugging hints.

**Comment by cadasa** [comment]
I've got exactly the same error - have you fixed yours?

**Comment by AiZUBI** [comment]
Not yet unfortunately. I'm digging deeper into selinux which seems to cause this issue. Have tried to change Ubuntu versions, disabling selinux and adjusting selinux policies. No success so far.  
Maybe @dusty-nv has an idea what may cause this issue.

**Comment by tokk-nv** [comment]
I confirmed I get the same error on `L4T_VERSION: 36.4.0`.
I will check.

**Comment by tokk-nv** [comment]
Hi,
Will you do this quick fix and see if that will solve the issue?

In `launch_jetson_copilot.sh`, replace `CONTAINER_TAG="r36.3.0"` to `CONTAINER_TAG="r36.4.0"`.

We actually have built and push the r36.4 container image.
When I tested with that it worked, so I probably need to fix the `launch_jetson_copilot.sh` to handle both revision of L4T.

**Comment by tokk-nv** [comment]
I merged this fix.
https://github.com/NVIDIA-AI-IOT/jetson-copilot/pull/16

We will need to build and update the Jetson-copilot image on jetson-containers.

**Comment by cadasa** [comment]
Thanks a lot! it works like a charm now

**Comment by helm-lab** [comment]
I can confirm the fix. Thx @tokk-nv

**Comment by chitoku** [comment]
Thank you, Cadasa and AiZUBI for checking.
I will work with @dusty-nv to rebuild and push the `jeston-containers` image.

**Comment by tokk-nv** [comment]
Thank you, Cadasa and AiZUBI for checking.
I will work with @dusty-nv to rebuild and push the `jeston-containers` image.
